### PR TITLE
Do not alias /server <hostname> to /server connect <hostname>

### LINKED ISSUE #559: Consider making /server <hostname> an error
Let's consider making `/server <hostname>` an error and make that behaviour available via `/server jump <hostname>` (or something similar).

I believe it's only IRC operators who are left who uses this - I might be wrong. Speak up if you rely on this behaviour :-)

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #559.
The old functionality is available by using `/server connect` as it was before.

### CODE REVIEW

**Comment by ailin-nemui** [comment]
any help needs updating?

**Comment by LemonBoy** [comment]
Good catch

**Comment by vague666** [comment]
Yeah, there is
feb 14 22:16:59     /SERVER chat.freenode.net
feb 14 22:16:59     /SERVER +chat.freenode.net
feb 14 22:16:59     /SERVER CONNECT chat.freenode.net
feb 14 22:16:59     /SERVER CONNECT +chat.freenode.net

File: src/core/chat-commands.c [hunk 1]
```diff
@@ -250,12 +250,6 @@ static void cmd_server(const char *data, SERVER_REC *server, WI_ITEM_REC *item)
 	command_runsub("server", data, server, item);
 }
 
-static void sig_default_command_server(const char *data, SERVER_REC *server,
-				       WI_ITEM_REC *item)
-{
-        signal_emit("command server connect", 3, data, server, item);
-}
-
 /* SYNTAX: SERVER [-4 | -6] [-ssl] [-ssl_cert <cert>] [-ssl_pkey <pkey>] [-ssl_pass <password>]
```
Comment (ailin-nemui) [inline src/core/chat-commands.c]: also here
