### PR TITLE
Fixed problem found by Coverity Scan

### LINKED ISSUE #981: Coverity static analysis scan results
Hi,

the following minor problems has been found by the Coverity Scan static analysis:
<pre>
Error: RESOURCE_LEAK (CWE-772): [#def1]
irssi-1.1.1/src/irc/core/irc-expandos.c:140: alloc_fn: Storage is returned from allocation function "expando_cumode".
irssi-1.1.1/src/irc/core/irc-expandos.c:121:17: alloc_fn: Storage is returned from allocation function "g_malloc".
irssi-1.1.1/src/irc/core/irc-expandos.c:121:17: var_assign: Assigning: "cumode" = "g_malloc(2UL)".
irssi-1.1.1/src/irc/core/irc-expandos.c:125:4: return_alloc: Returning allocated memory "cumode".
irssi-1.1.1/src/irc/core/irc-expandos.c:140: var_assign: Assigning: "ret" = storage returned from "expando_cumode(server, item, free_ret)".
irssi-1.1.1/src/irc/core/irc-expandos.c:141: leaked_storage: Variable "ret" going out of scope leaks the storage it points to.
#  139|   
#  140|   	ret = expando_cumode(server, item, free_ret);
#  141|-> 	return *ret == '\0' ? " " : ret;
#  142|   }
#  143|   
</pre>
I think, it should de-allocate ret when returning " ".

<pre>
Error: RESOURCE_LEAK (CWE-772): [#def2]
irssi-1.1.1/src/irc/dcc/dcc-send.c:387: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function has been overridden by a user model.]
irssi-1.1.1/src/irc/dcc/dcc-send.c:387: var_assign: Assigning: "hfile" = handle returned from "open(str, 0)".
irssi-1.1.1/src/irc/dcc/dcc-send.c:396: noescape: Resource "hfile" is not freed or pointed-to in "fstat". [Note: The source code implementation of the function has been overridden by a builtin model.]
irssi-1.1.1/src/irc/dcc/dcc-send.c:428: leaked_handle: Handle variable "hfile" going out of scope leaks the handle.
#  426|   	if (dcc == NULL) {
#  427|   		g_warn_if_reached();
#  428|-> 		return FALSE;
#  429|   	}
#  430|   
</pre>
I think it should close hfile.

Also there is ticket #197 about enabling integration with coverity.

### PR DESCRIPTION
**Pull request by yarda**
Fixes #981

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

File: src/irc/core/irc-expandos.c [hunk 1]
```diff
@@ -138,7 +138,7 @@ static char *expando_cumode_space(SERVER_REC *server, void *item, int *free_ret)
                 return "";
 
 	ret = expando_cumode(server, item, free_ret);
-	return *ret == '\0' ? " " : ret;
```
Comment (ailin-nemui) [inline src/irc/core/irc-expandos.c]: ret must not be freed unless free_ret is set. Probably it won't ever be set if *ret is 0

**Comment by dequis** [comment]
I guess the PR title is outdated, right?

**Comment by yarda** [comment]
It was OK in the commit itself, I changed the title here manually.
